name: Release

on:
  push:
    tags:
    - '*'

jobs:
  lint:
    name: Release Stylesheet
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Get Yarn cache path
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Setup node
        uses: actions/setup-node@master
        with:
          node-version: 16.x

      - name: Load Yarn cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build SCSS
        run: yarn build

      - uses: ncipollo/release-action@v1
        with:
          artifacts: "css/**/*.css"
          token: ${{ secrets.GITHUB_TOKEN }}